# Generated by Django 6.0.3 on 2026-03-27 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('issue_type', models.CharField(choices=[('MISSED_COLLECTION', 'Missed Collection'), ('ILLEGAL_DUMPING', 'Illegal Dumping'), ('DAMAGED_BIN', 'Damaged Bin'), ('OTHER', 'Other')], default='MISSED_COLLECTION', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reports/photos/')),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('contact_preference', models.CharField(choices=[('SMS', 'SMS'), ('APP', 'App Notification')], default='APP', max_length=3)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('VERIFIED', 'Verified')], default='RECEIVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to='reports.report')),
            ],
        ),
    ]
