# Generated by Django 6.0.3 on 2026-03-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='assigned_crew',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
