# Generated by Django 6.0.3 on 2026-03-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_assigned_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tracking_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
