# Generated by Django 6.0.3 on 2026-03-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_report_issue_type_verification_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='issue_type',
            field=models.CharField(choices=[('MISSED_COLLECTION', 'Missed Collection'), ('ILLEGAL_DUMPING', 'Illegal Dumping'), ('OVERFLOWING_BIN', 'Overflowing Bin'), ('LITTERING', 'Littering'), ('POTHOLE', 'Pothole'), ('WATER_LEAK', 'Water Leak'), ('ELECTRICITY_OUTAGE', 'Electricity Outage'), ('OTHER', 'Other')], default='MISSED_COLLECTION', max_length=50),
        ),
    ]
